name: 'AWS CFN Validator'
description: 'Validates some cloudformation yaml files in an specified location'

inputs:
  target:
    required: false
    default: '*.yaml'
  location:
    reuired: false
    default: '.'
  region:
    required: false
    default: us-east-1
  profile:
    required: false
    default: default
  credentials:
    required: false
    default: /root/.aws/credentials
  outputdir:
    required: false
    default: validations

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Validation
      shell: bash
      env:
        AWS_REGION: ${{ inputs.region }}
        AWS_PROFILE: ${{ inputs.profile }}
        AWS_SHARED_CREDENTIALS_FILE: ${{ inputs.credentials }}
      working-directory: ${{ inputs.location }}
      run: |
        mkdir ${{ inputs.outputdir }}
        for TARGET in $(ls ${{ inputs.target }}); do
          aws cloudformation validate-template \
          --template-body file://$(pwd)/$TARGET | \
          tee ${{ inputs.outputdir }}/${TARGET%.*}.json
        done
    - name: Register Validator Evidence
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: aws-cfn-validate-evidence
        path: ${{ inputs.location }}/${{ inputs.outputdir }}/
