name: Slack Notify
description: Notify GitHub Workflow Status in a Slack Channel

inputs:
  token:
    required: true
  webhook:
    required: true

runs:
  using: composite
  steps:
    - name: Get Workflow Status
      uses: unitecicd/workflow-status@main
      id: check
      with:
        token: ${{ input.token }}
    - name: Notify Status by Slack
      uses: rtCamp/action-slack-notify@v2
      env:
       SLACK_COLOR: ${{ steps.check.outputs.status }}
       SLACK_WEBHOOK: ${{ inputs.webhook }}
