name: Slack Notify
description: Notify GitHub Workflow Status in a Slack Channel

inputs:
  status:
    required: true
  webhook:
    required: true

runs:
  using: composite
  steps:
  - name: Notify Status by Slack
    uses: rtCamp/action-slack-notify@v2
    env:
     SLACK_COLOR: ${{ inputs.status }}
     SLACK_WEBHOOK: ${{ inputs.webhook }}
