name: 'Groovy Lint'
description: 'Lint some Groovy files in an specified location'

inputs:
  failon:
    required: false
    default: 'error'
  outputfile:
    required: false
    default: ./lint.txt
  outputjson:
    required: false
    default: ./lint.json

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Lint
      shell: sh
      run: |
        echo "npm-groovy-lint (https://github.com/nvuillam/npm-groovy-lint)"
        npm-groovy-lint --config recommended-jenkinsfile --noserver --failon ${{ inputs.failon }} | \
        tee ${{ inputs.outputfile }}
        npm-groovy-lint --noserver --output json > ${{ inputs.outputjson }}
    - name: Register Linter Evidence
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: groovy-lint-evidence
        path: |
          ${{ inputs.outputfile }}
          ${{ inputs.outputjson }}
