name: Auto Request Review

on:
  pull_request:
    types:
    - opened
    - ready_for_review
    - reopened

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
    - name: Request reviews
      uses: necojackarc/auto-request-review@master
      with:
        token: ${{ secrets.UNITE_GH_TOKEN }}
        config: .github/reviewers.yml
